version: "3.9"

services:
  ble2wled:
    image: ble2wled
    restart: unless-stopped
    network_mode: host
    environment:
      WLED_HOST: wled.local
      LED_COUNT: 60
      MQTT_BROKER: localhost
      MQTT_LOCATION: balkon
      MQTT_PORT: 1883
      MQTT_USERNAME: espresense
      MQTT_PASSWORD: your_secure_password
      LOG_LEVEL: INFO
